### ISSUE TITLE
Peggle Deluxe Steam not working

### ISSUE THREAD

**Issue by g3nsvrv** [the1812/Popcap-Patches#1]
![image](https://user-images.githubusercontent.com/11720535/88986511-32149a00-d2a1-11ea-958b-ec02572dda9e.png)

**Comment by the1812** [comment]
Could you upload `Peggle.exe`? I don't have this game's files.

**Comment by g3nsvrv** [comment]
sure 
[Peggle.zip](https://github.com/the1812/Popcap-Patches/files/5011050/Peggle.zip)

**Comment by the1812** [comment]
You can try add 2 more `*` in _Advanced Options > Video Card Check Pattern_


<img height="700" src="https://user-images.githubusercontent.com/26504152/89114347-eaaf2900-d4ad-11ea-82c0-41416bd123d4.png">

**Comment by g3nsvrv** [comment]
that works!!!! amazing!

![image](https://user-images.githubusercontent.com/11720535/89115337-4ac5b100-d455-11ea-9e2f-70660200977c.png)
