### ISSUE TITLE
[Unable to load Steam.dll Error] Peggle Deluxe and Peggle Nights Steam Version

### ISSUE THREAD

**Issue by CahosRahneVeloza** [the1812/Popcap-Patches#6]
I encountered the above error after patching the original Steam versions of the application files for Peggle Deluxe and Peggle Nights, is there any way to fix this?

**Comment by the1812** [comment]
This is a common problem caused by updated Steam, and there are many solutions in Steam Community.
https://steamcommunity.com/sharedfiles/filedetails/?id=2328380020

**Comment by CahosRahneVeloza** [comment]
Hey thanks for the link man. That did the trick :)

Consider this issue post closed :)
